/**
 * NekoAdvance - Version Management based on Commit Count
 * Automatically generated by pre-commit hook.
 */

export const CURRENT_COMMITS = 41;

export function calculateVersion(commits) {
  const major = Math.floor(commits / 100) + 1;
  const remainder = commits % 100;
  const minor = Math.floor(remainder / 10);
  const patch = remainder % 10;
  
  if (remainder === 0) {
    return `${major}.0.0 (beta)`;
  }
  return `${major}.${minor}.${patch}`;
}

export const APP_VERSION = calculateVersion(CURRENT_COMMITS);
