#!/bin/bash
# NekoAdvance - Auto-Versioning Hook
COMMITS=$(($(git rev-list --count HEAD 2>/dev/null || echo 38) + 1))

cat << INNER_EOF > js/core/version.js
/**
 * NekoAdvance - Version Management based on Commit Count
 * Automatically generated by pre-commit hook.
 */

export const CURRENT_COMMITS = ${COMMITS};

export function calculateVersion(commits) {
  const major = Math.floor(commits / 100) + 1;
  const remainder = commits % 100;
  const minor = Math.floor(remainder / 10);
  const patch = remainder % 10;
  
  if (remainder === 0) {
    return \`\${major}.0.0 (beta)\`;
  }
  return \`\${major}.\${minor}.\${patch}\`;
}

export const APP_VERSION = calculateVersion(CURRENT_COMMITS);
INNER_EOF

# Update Service Worker Cache Name
sed -i "s/const CACHE_NAME = 'nekoadvance-rolling-v[0-9]*';/const CACHE_NAME = 'nekoadvance-rolling-v${COMMITS}';/g" sw.js

git add js/core/version.js sw.js 2>/dev/null || true
